--- 
description: "Greet someone and record the time"
inputs: 
  who-to-greet: 
    default: World
    description: "Who to greet"
    required: true
name: "Hello World"
outputs: 
  time: 
    description: "The time we greeted you"
runs: 
  args: 
    - "${{ inputs.who-to-greet }}"
  image: Dockerfile
  using: docker
